language: python

python:
  - "3.6"

install:
  - pip install -q yapf==0.28.0
  - pip install -q -r requirements.txt

script:
  - yapf -drp pyroclast --style=".style.yapf"
  - pytest pyroclast

notifications:
  slack: unldeeplearning:Rlua358rgewVz3KouHODYK8w
